# Generated by Django 4.2.19 on 2025-02-09 22:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DateTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateTime', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='GuestName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='MyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('place', models.CharField(choices=[('outside', 'Outside'), ('inside', 'Inside')], default='outside', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=2)),
                ('place', models.CharField(choices=[('outside', 'Outside'), ('inside', 'Inside')], default='outside', max_length=10)),
                ('number', models.DecimalField(decimal_places=2, max_digits=2)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guestNumber', models.PositiveIntegerField()),
                ('dateTime', models.DateTimeField()),
                ('lastname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.guestname')),
                ('number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.table')),
            ],
        ),
    ]
