# Generated by Django 5.1.6 on 2025-02-10 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_table_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
    ]
