# Generated by Django 5.1.6 on 2025-02-10 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_table_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='number',
            new_name='TableNumber',
        ),
        migrations.RenameField(
            model_name='table',
            old_name='number',
            new_name='TableNumber',
        ),
    ]
